server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
springdoc:
  api-docs:
    path: /api-docs
spring:
  application:
    name: bs-pet-store-v1
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 12345
#  kafka:
#    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: SCRAM-SHA-256
#        jaas:
#          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="rb1j5rt0" password="R9oqA5r52g5TJoYxd6S_I3xrE9XGQ2gQ";
#  cloud:
#    function:
#      definition: input
#    stream:
#      bindings:
#        input-in-0:
#          destination: rb1j5rt0-updaccount
#        input-in-1:
#          destination: rb1j5rt0-updaccountbc
#        output-out-0:
#          destination: rb1j5rt0-yankiout

#eureka config
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8082/eureka/
#    enabled: true
#  instance:
#    hostname: localhost
#feign config
#bp:
#  service:
#    url: 'http://localhost:9090/BusinessPartnerService'
#cc:
#  service:
#    url: 'http://localhost:9092/Credits'
